# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page/:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown
disqus: ac-blog
google_analytics: UA-32450507-1
permalink: /:title

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: "Arnaud Camus"

title: "Arnaud Camus"
description: Personal website where I share about technology, leadership and other topics important to me.
author:
  name: "Arnaud Camus"
  github: lynfogeek
  twitter: lynfogeek
  linkedin: arnaudcamus
  bio: "Engineering Leader • Entrepreneur • Co-founder of Impraise (YC S14)"
  email_md5: e9a0cebdef838ecfa24fc079b3ddc134
site:
  url: https://arnaud-camus.fr/
url: https://arnaud-camus.fr/

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:

#plugins
gems: [jekyll-paginate]
